---
layout: post
read_time: true
show_date: true
title:  CPP异常知识碎片
date:   2021-01-25 13:32:20 -0600
description: CPP异常处理的处理逻辑与种类
img: posts/20220214/leaves.png
tags: [c++, exeption]
author: DD
mathjax: yes
---


<center><img src="./assets/img/posts/20220214/exception_list.png" width="480px"></center>

图片取自csdn @任我驰骋

首先异常全部继承自std::exception类
抓几个重要的来说，
std::bad_alloc在表征内存开辟错误
std::bad_cast 主要是dynamic_cast过程中抛出的错误。
logic_error 溢出、语义错误等
std::runtime_error 运行时错误，溢出错误

*  std::overflow_over
*  std::range_error
*  ...

异常捕捉的标准凭证是throw()

```
//异常处理标准流程

try {
} catch (Exception &) {

}
```
   
 关于异常处理的标准流程：
 

*  首先检查throw是否本身在try语句块内
*  如果在则选择匹配的catch进行处理，如果没有找到匹配的catch或者本函数调用没有存在异常处理，递归地退出当前函数帧栈寻找catch解决，
*  直到退出到main函数层面，如果依然没有匹配的处理模块那么就终止程序

**异常安全**

构造函数完成对象的构造和初始化，最好不要在构造函数中抛出异常，否则可能导致对象不完整或没有完全初始化

析构函数主要完成资源的清理，最好不要在析构函数内抛出异常，否则**可能导致资源泄漏(**内存泄漏、句柄未关闭等)

C++中异常经常会导致资源泄漏的问题，比如在new和del
ete中抛出了异常，导致内存泄漏，在lock和unlock之间抛出了异常导致死锁，C++经常使用RAII来解决以上问题。

异常抛出规范

```
// 这里表示这个函数会抛出A/B/C/D中的某种类型的异常
void fun() throw(A，B，C，D);
// 这里表示这个函数只会抛出bad_alloc的异常
void* operator new (std::size_t size) throw (std::bad_alloc);
```

更详细的观点链接： https://blog.csdn.net/mz474920631/article/details/125019151

异常的几个缺点记一下：比较重要的
- 程序乱跳
- C++没有垃圾回收，异常中没有正确处理申请的内存会很危险
- C++标准库的异常体系其实有点乱
- 异常尽量规范使用，否则后果不堪设想，随意抛异常，外层捕获的用户苦不堪言。所以异常规范有两点：一、抛出异常类型都继承自一个基类。二、函数是否抛异常、抛什么异常，都使用 func（）throw();的方式规范化。